### ISSUE TITLE
Request sometimes fails with {"message": "Database \"crexi-lease-stage\" does not exist!"}

### ISSUE THREAD

**Issue by DzmVasileusky** [recombee/js-api-client#11] opened 2021-03-12 10:41 UTC
We are using recombee-js-api-client version 3.0.1.
Sometimes (rare) request to our service hosted on recombee fails with error
```{"message": "Database \"crexi-lease-stage\" does not exist!"}```
Request
https://client-rapi-crexi.recombee.com/crexi-lease-stage/detailviews/?frontend_timestamp=1615545487&frontend_sign=8b193e0e2260fdc93a6c4031cd39d73373e46992

Integration code
```
class RecombeeService {

  constructor () {
    const options = { baseUri : 'client-rapi-crexi.recombee.com' };
    this.client = new recombee.ApiClient(CONFIG.recombeeDBId, CONFIG.recombeeToken, options);
  }
  
  trackPropertyVisitor (userId: string, assetId: number | string, recommId?: string) {

        this.client.send(new recombee.AddDetailView(userId, assetId, {
            cascadeCreate: true, recommId
        }));

    }

}
```

**Comment by OndraFiedler** [comment] 2021-03-12 11:19
Hi,
according to a support request by one of your colleagues, the `crexi-lease-stage` has been transferred to the US (and thus started to work with `client-rapi-crexi.recombee.com`) ca one hour ago.

I think you should not be getting this error since, but if you do please contact support@recombee.com. The issue would not be caused by the JS client, but would be somewhere else.

**Closed as completed by OndraFiedler** 2021-03-12 11:19 UTC
